### PR TITLE
Catchup

### PR DESCRIPTION
**Pull request by moonglum**
This was an eventful year :heart: It's really incredible to know so many amazing people and see so many great places. Thanks @bascht for creating this project so I can reflect on that from time to time :heart: 

For details, you need to check out the commit messages :smile:

### CODE REVIEW

**Comment by bascht** [comment]
:heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished: :heart: :astonished:

**Comment by bascht** [comment]
Most remarkably: Stag night in Heide. 

:D

**Comment by moonglum** [comment]
:heart: Thanks for the merge :heart: 

Yep, there's basically no better place for stag night than Heide :laughing:

**Comment by skade** [comment]
screen shot 2016-01-18 at 10 43 52

Mail.app, unable to handle the cuteness.

**Comment by moonglum** [comment]
Woha :laughing: Especially funny as there are only two kind of Emojis in the hole message :wink:

**Comment by bascht** [comment]
Also: That little jumpin' fellow: 
screenshot-cloud githubusercontent com 2016-01-18 11-46-47

**Pull request merged**
