### PR TITLE
super Idee, ich will auch :)

### PR DESCRIPTION
**Pull request by jkraemer**

### CODE REVIEW

**Comment by bascht** [comment]
Thats an opinionated twitter handle, you have there! :D Welcome aboard!

**Comment by skade** [comment]
I hope @jkraemer never has to write Rust code. (4SpaceNoTabs)

**Comment by bascht** [comment]
Or Python. `4_spaces_no_tabs_and_snake_cased`.

**Comment by annismckenzie** [comment]
Or Go. `4_spaces_tabs_and_camel_cased`.

**Comment by skade** [comment]
Actually `4_spaces_tabs_and_camel_caps_when_public_and_camel_back_when_private`.

**Comment by bascht** [comment]
More like: `2_camels_and_no_caps_but_tab_likeNobodyIsWatching`

**Pull request merged**
