### PR TITLE
bodo in australia

### PR DESCRIPTION
**Pull request by bitboxer**
Hello dear travellers,

I have been in Australia. It was awesome. Sydney is sadly kindy meh, but Melbourne is awesome. I would totally do this trip again, but with less days in Sydney and more in Melbourne. Did I already say that Melbourne is great? No? 

And the stuff between the cities is awesome, too. The great ocean road and the Grampians are a must visit if you cruise around South Australia. 

Here, have a koala:

20151007-pa070540

### CODE REVIEW

**Comment by skade** [comment]
noʎ ɹoɟ ʇı pǝxıɟ 'ǝɹnʇɔıd ɹnoʎ uı ɹoɹɹǝ uɐ s,ǝɹǝɥʇ

d651dabe-78f2-11e5-84a1-3cc334573083

**Comment by bitboxer** [comment]
hm, it is merged, but the page does not have the new data on it :sob: .

**Comment by skade** [comment]
I think @bascht can deploy.

**Comment by bitboxer** [comment]
[ich rufe dich galaktika](https://www.youtube.com/watch?v=oaKrRJF6BrA&feature=youtu.be&t=4m9s)

**Comment by bascht** [comment]
Weeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeellllllllll. This *should* be deployed automatically. At the moment I have little to no idea which build service / did this, but I'll be happy to report back once I found it.

**Comment by bitboxer** [comment]
Etoomanydeploymenttools

**Comment by bascht** [comment]
So, I'm pretty sure I did set up a build server in Tondorf – ages ago. It might be gone. It might come back anytime soon. Anyways. Deploys are now triggered directly via Heroku:

screenshot from 2015-10-23 07-45-15

**Comment by bascht** [comment]
That might have worked. Looks appropriate.

screenshot from 2015-10-23 08-00-12

**Comment by bitboxer** [comment]
Great! Thanks :+1:

**Pull request merged**
