### PR TITLE
Another conf, another city

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by bascht** [comment]
Was your talk recorded? (Oh. By the way: Three way merge over here: https://github.com/findoutwho/hasbeen.at/blob/master/config/attendees/badboy.yaml) ;)

**Comment by badboy** [comment]
Yes it was, still waiting for the video though.

**Comment by badboy** [comment]
What's with the "three way merge"?

**Comment by bascht** [comment]
The conf is missing from your hasbeen.at site. ;)

**Comment by badboy** [comment]
Only because [it's not merged yet](https://github.com/findoutwho/hasbeen.at/pull/23/files)

**Comment by bascht** [comment]
*pokes @schultyy with-a-pointy-stick*

**Comment by schultyy** [comment]
It is [merged now](https://github.com/findoutwho/hasbeen.at/pull/23) 💃🏻🙆🏽

**Pull request merged**
