### PR TITLE
add flag for current hometown

### PR DESCRIPTION
**Pull request by dojobo**
addresses #122 by adding current_hometown to the user's profile (a blue marker on the map). i liked the idea of adding it to this part of the yaml better than making up a new kind of hash in the locations, but it meant a little more wrangling for the hometown to get recognized as another location. also added an optional :special attr to Location, used here for current hometown, but could be used for other things as well (birthplace, wishlist...)

### CODE REVIEW

**Comment by dojobo** [comment]
belated refactor idea is to make a new class of Location, CurrentHometown, and instead ask locations if they are a CurrentHometown. i think this would be a bit cleaner and also not violate the open/closed principle.

**Comment by bascht** [comment]
Currently on the road – but this sounds very good! Thanks! :)
/paging @annismckenzie for a review.

**Comment by annismckenzie** [comment]
I'm here. Already read through the code but wanted to wait for @bascht's approval.

Talk about a chicken and egg. :D

**Comment by bascht** [comment]
It's almost lunch time, I'd rather have the chicken.
@annismckenzie if you don't have any objections: Merge away!

**Comment by annismckenzie** [comment]
Me too. :chicken:

I like it – thanks for the implementation!

when-he-introduced-you-his-hometown

**Comment by bascht** [comment]
:heart_decoration: :heart_decoration: :heart_decoration:

**Comment by dojobo** [comment]
thanks guys :grin:

**Comment by annismckenzie** [comment]
No, thank you!

**Pull request merged**
