### PR TITLE
Bodo in Ottawa 🇨🇦

### PR DESCRIPTION
**Pull request by bitboxer**
I am in the nice Canada this week. First a couple of nice days in Montreal to see a 👶 and now visiting the capital to check it from my list.

### CODE REVIEW

**Comment by moonglum** [comment]
Awesome :) :)

**Comment by bascht** [comment]
Wait wait wait wait wait.
All checks have passed but my internal consistency engine is not yet satisfied. You visited Montreal by staying in Ottawa and watching a :baby:?

**Comment by bitboxer** [comment]
I visited Montreal and the Ottawa and will now return to Montreal to catch my flight tomorrow. But Montreal is already in the file and because of that I only have this one city to add :wink:

**Comment by bascht** [comment]
@bitboxer Niiiiice. Refreshing my INBOX right now for hot insider locations in Toronto & Montreal. Going there in 3 weeks! :earth_americas:

**Comment by bascht** [comment]
@bitboxer Still refreshing my INBOX. :smile_cat:

**Comment by bitboxer** [comment]
Still on vacation, will answer soon.

**Comment by bascht** [comment]
@bitboxer I'm so exited. And I just couldn't hide it. And I know
I know.
I know.
I know.
I know.
I want Hints! :dancer:

(No worries: Enjoy your days off! :smiley:)

**Comment by bitboxer** [comment]
Things you should do: 

* Get to the Atwater Market (buy maple sirup cans) and walk on the Canal there
* Go to the Café Bloom (not far from there) and get a Waffle with Maple Sirup.
* Underground City for shopping
* If you never had a Five Guys Burger, there are plenty of them in Downtown
* Check out the music scene. The jazz fest is amazing. You are too early for that, right?
* Stay away from the pizza. Just don't. They can't make them here. 
* Go to the Chalet du Mont Royal. Nice little hike up and amazing view above the city
* Walk around the old harbour
* Tacos Victor has really good Tacos.
* Get a poutine somewhere.
* And beaver tails.

**Comment by bascht** [comment]
@bitboxer :heart_eyes_cat: :gift_heart: Thank you so much! We're a bit too early for the Jazz festival, but that list is already great enough! <3

**Comment by bitboxer** [comment]
I was in Toronto for 2 nights 5 years ago, sadly I don't have anything that I can recommend in my head right now. Was not too impressed about that city. Very business-y.

**Pull request merged**
