### PR TITLE
Update sternenseemann.yml

### PR DESCRIPTION
**Pull request by sternenseemann**

### CODE REVIEW

**Comment by bascht** [comment]
Niiice. Just casually dropping an :icecream:-land visit. :smiley:

**Comment by sternenseemann** [comment]
Well of course :D Was great, although I just missed jsconf by a few days. :(

**Comment by bascht** [comment]
That's a bit of a bummer. Are you at JS Kongress Munich though?

**Comment by sternenseemann** [comment]
Dunno, I am not really into JS but I would have gone there I guess.

**Pull request merged**
