### PR TITLE
Added my traveller file

### PR DESCRIPTION
**Pull request by cgie**

### CODE REVIEW

**Comment by bascht** [comment]
*Aberystwyth*. Finally someone takes care of adding more consonants to hasbeen.in! Great to have you aboard! :)

**Comment by bascht** [comment]
Nice, the Heroku trigger is back up again. It's alive! http://cgie.hasbeen.in :smile_cat:

**Comment by annismckenzie** [comment]
:dancers:

**Comment by cgie** [comment]
Pretty cool, thanks!

**Pull request merged**
