### PR TITLE
Badboy summer travel

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by moonglum** [comment]
😍😍😍

**Comment by annismckenzie** [comment]
Just some casual around-the-corner-of-your-hood type of travels I see. 🤣 

Shall I merge it?

**Comment by badboy** [comment]
Yes please

**Comment by annismckenzie** [comment]
Huh, that worked although buildheroes.com is kinda offline. Gotta ask Mr. @bascht what's up with that.

**Comment by bascht** [comment]
Finally, here's the Yaml-Part of all those fancy Instagram shots. 😺

**Pull request merged**
