### PR TITLE
Add Vienna to onkelhotte.yml \o/

### PR DESCRIPTION
**Pull request by klausmeyer**
Finally after planning it for all my previous vacations I've been in Vienna for a couple of days.
Just for sightseeing.

After arrival by car (about 500km / 5-6 hours from my hometown) I was quite sleepy but at least I checked out the location of my hotel a bit and went for Dinner in a nearby location: Austrian beer and [Kaiserschmarrn][1] - what a combination :laughing:.

On the second day I discovered the city a bit on my own by using the subway which was very handy since my hotel was just at the [Prater][2] :ferris_wheel: and it's station. Finally on the third and last day I decided to do the most tourist-like thing you can do to sightseeing: A hop-on-hop-off bus-tour.

I can only recommend visiting Vienna: It's a wonderful city with fantastic sights.

[1]: https://en.wikipedia.org/wiki/Kaiserschmarrn
[2]: https://en.wikipedia.org/wiki/Prater

### CODE REVIEW

**Comment by bascht** [comment]
Sounds like a great trip! Did you try [Eitrige](https://en.wikipedia.org/wiki/Carniolan_sausage) ? :D

**Comment by klausmeyer** [comment]
Of course ... or how they in Vienna would say: "eh klar!" ;)

**Comment by bascht** [comment]
I think @pxlpnk will approve. :+1:

**Comment by pxlpnk** [comment]
eh kloar! Don't forget the sechzehnerblech!

**Comment by klausmeyer** [comment]
I even took some sechzehnerblech home with me to Bavaria (don't tell anyone :grinning:).

**Pull request merged**
