### PR TITLE
eljojo: added more cities

### PR DESCRIPTION
**Pull request by eljojo**
hallöchen, the last months have been a bit busy!

Thank for maintaining this <3

### CODE REVIEW

**Comment by bascht** [comment]
Niiiice. *bracing-myself-for-more-canadian-cities-to-come*. :)

**Comment by bascht** [comment]
\o/

After fixing #131 deployment is working again! :sparkle: http://eljojo.hasbeen.in/Valdivia

**Comment by eljojo** [comment]
yeay thanks! I noticed it wasn't working after merging, but I didn't want to bug you :)

**Comment by bascht** [comment]
You sound like the perfect user to have. :dancers:

**Comment by eljojo** [comment]
:blush:

**Pull request merged**
