### PR TITLE
add home button to profiles & dev env tweaks

### PR DESCRIPTION
**Pull request by dojobo**
re: #92, i struggled with the most elegant way to add this, e.g. by changing the index route in the controller, but couldn't figure out how to inject the proper username. a new route with a redirect didn't work either (since /:location was already in use) so here you have my solution :)

also, not sure if this is just me, but when i rackup with no args it's on port 9292, so i put this in the dev url template. however the readme still says 3000.

### CODE REVIEW

**Comment by dojobo** [comment]
forgot to write the .sub(/regex/) for home_link while on map.erb. started to add it but then decided it made more sense to remove the link anyway; going back to the user profile first is the more sensible path.

**Comment by annismckenzie** [comment]
:dancers:

**Comment by bascht** [comment]
Niiiice. Thanks for taking a look at this! Re the port: if you start it with `rackup`, you'll get the Rack port 9292. Use `bundle exec padrino start` to fire it up on port 3000.

Gonna merge merge merge this one. (closes #92)
thanks!

**Comment by dojobo** [comment]
ah, thanks for the tip!

**Pull request merged**
