### PR TITLE
WHO WANTS FASTER BUILDS?

### PR DESCRIPTION
**Pull request by annismckenzie**
…said no one ever in particular.

Still, Travis offers it out of the box – taking it for a spin.

### CODE REVIEW

**Comment by annismckenzie** [comment]
Alright, this took 2:40min. Let's take a look at the second one.

**Comment by annismckenzie** [comment]
Whoa, **18 seconds** on the second one.

**Comment by annismckenzie** [comment]
As far as I can see there's no side-effects. Travis uploads the bundle's cache to S3 and downloads it when starting the build. Changes to the Gemfile are tracked properly and the cache is then updated.

**Comment by bascht** [comment]
This is amazing! :dancer: SPEED + STYLE FIXES!

ME LIKEY! <345

**Pull request merged**
