### PR TITLE
Remove `sensor` parameter from Google Maps script element

### PR DESCRIPTION
**Pull request by annismckenzie**
See #137 for more information.

### CODE REVIEW

**Comment by annismckenzie** [comment]
@bascht: can you deploy this to the staging environment? 😂

**Comment by annismckenzie** [comment]
Travis:
»This job is running on our new platform for *Legacy Precise* builds. Please read [our blog post for more information](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future).«

:dancers: Here's to legacy!

**Comment by bascht** [comment]
Sure. I'll…just…deploy…that… to our _invisible_ staging environment.

https://media4.giphy.com/media/ZgnxpjzA8AUFi/200.gif

**Comment by bascht** [comment]
Here's to legacy! *clink*
#139

**Pull request merged**
