### PR TITLE
Bodo in Scandinavia

### PR DESCRIPTION
**Pull request by bitboxer**
I traveled a bit. I visited Copenhagen (which is beautiful) and took a
train to Stockholm (which I didn't like that much). Due to a train
problem I ended up in Malmö for 2 hours (which is also beautiful from
what I could see).

One little note for Stockholm: If you ever plan to visit a usergroup
there, don't show up in a nerd shirt. You will be the only one and feel
underdressed. Yes, even on a JS usergroup :wink:.

### CODE REVIEW

**Comment by bascht** [comment]
Best thing about Stockholm: Proper 🐟 'n 🍟 .

**Comment by bitboxer** [comment]
Sadly the fish and chips Inhad have been mediocre. You should have given me the details where to find good ones 😢

**Comment by bascht** [comment]
### Fun fact №1
I felt underdressed the whole time, no matter where we went. It got worse in Oslo.
### Fun fact №2
I just rechecked our photos… …aaaaaaand it wasn't Stockholm, but Oslo that had the best Fish'n Chips ever. Period. So – once you're in Oslo, go visit [Fiskeriet fiskebutikk](https://www.google.de/maps/place/Fiskeriet+fiskebutikk/@59.9145504,10.7496728,3a,75y,90t/data=!3m8!1e2!3m6!1s-xJGCS5bLjqk%2FWCs3tgZCgKI%2FAAAAAAAAAE4%2FbpLtsyEYwFctt887KUDlSJzyqthLhUfvwCLIB!2e4!3e12!6s%2F%2Flh5.googleusercontent.com%2F-xJGCS5bLjqk%2FWCs3tgZCgKI%2FAAAAAAAAAE4%2FbpLtsyEYwFctt887KUDlSJzyqthLhUfvwCLIB%2Fs203-k-no%2F!7i5128!8i2860!4m8!1m2!2m1!1sfish'n+chips+in+oslo!3m4!1s0x0:0x12bb736bae11e81d!8m2!3d59.9145608!4d10.7496554!6m1!1e1?hl=en).

**Comment by bitboxer** [comment]
Thanks. Marked as todo 👍

**Pull request merged**
