### PR TITLE
Reorganize cities and add a few missing

### PR DESCRIPTION
**Pull request by eljojo**
👋  decided to reorg the cities, also added a couple more ✈️ 🌏 🌎

### CODE REVIEW

**Comment by eljojo** [comment]
🎩  "works on my computer"
screen shot 2017-10-22 at 12 44 40

**Comment by annismckenzie** [comment]
Nice spring cleaning you did there!

**Comment by annismckenzie** [comment]
Merging if you're done?

**Comment by eljojo** [comment]
Danke! Yeah, go for it :)

**Comment by bascht** [comment]
@annismckenzie Thanks! 
@eljojo Hope to see _Tegernsee_ in there, someday soon. 😸

**Pull request merged**
